### ISSUE TITLE
[d3] Use abstract base classes to define interfaces in operators.py

### ISSUE THREAD

**Issue by namurphy** [DedalusProject/dedalus#130]
I was checking in on #118, and noticed that in `operators.py` there's a [comment](https://github.com/DedalusProject/dedalus/blob/06dd8ac08a132fb48c0cd4f2202e32889646884c/dedalus/core/operators.py#L728-L745) that says that certain attributes have to be defined for subclasses of `SpectralOperator`, `LinearOperator`, and `FutureField`.  

A way to refactor this would be by using [abstract base classes](https://docs.python.org/3/library/abc.html).  The parent class would inherit from `abc.ABC` (short for **A**bstract **B**ase **C**lass), and the required attributes/methods would be decorated with `@abc.abstractmethod`.  Subclasses would have to implement each of the attributes...otherwise they would not be able to be instantiated.

```Python
>>> from abc import ABC, abstractmethod

>>> class AbstractInterface(ABC):
...     @abstractmethod
...     def required_attribute(self):
...         ...

>>> class FirstSubclass(AbstractInterface):  # does not define the required attribute
...     pass
>>> FirstSubclass()
TypeError: Can't instantiate abstract class FirstSubclass with abstract method required_attribute

>>> class SecondSubclass(AbstractInterface):
...     def required_attribute(self):  # subclass defines the required attribute
...         return 42

>>> SecondSubclass()
<__main__.SecondSubclass object at 0x7f77a5b4e670>
```
Defining the abstract interface in code is preferable to defining it in comments, as comments have a nasty habit of not getting updated when the corresponding code changes.  They're also a way of enforcing that interfaces get adhered to.  (Also, they end up being really fun to use once we get used to them.)

**Comment by kburns** [comment]
Hi Nick.  Dedalus makes extensive internal use of custom metaclasses, so we generally avoid dependencies like ABC that also rely on metaclasses since this creates metaclass conflicts that are hard to resolve (for this reason, PR #131 fails on import).  Instead, we usually just define base class methods that simply raise a `NotImplementedError`, although we probably don't have complete coverage for these.  If a subclass is missing an expected attribute (like those outlined in the comments here), we usually find the resulting `AttributeError` to be sufficiently precise and descriptive, so I'm not sure more machinery around those is worthwhile (e.g. even besides the metaclass conflicts, the `abc` approach using `@property` with `@abstractmethod` adds 4+ lines of boilerplate per attribute!).

We definitely appreciate the feedback on the code, though. The `d3` branch is still in a rough alpha stage and there will be a lot of clean up and restructuring in the next few weeks here before we send it to beta, so it might not be worth it to comb through things too carefully quite yet!

**Comment by namurphy** [comment]
> Dedalus makes extensive internal use of custom metaclasses, so we generally avoid dependencies like ABC that also rely on metaclasses since this creates metaclass conflicts that are hard to resolve

Ah, that makes sense!  I just happened to be looking through that file and came across those comments.  We can close this issue too.

> (e.g. even besides the metaclass conflicts, the `abc` approach using `@property` with `@abstractmethod` adds 4+ lines of boilerplate per attribute!).

One general thought is that I usually try to gauge code readability rather than number of lines, and also whether or not code is easy to change.  While abstract base classes do tend to have several lines per attribute, I can usually scan through these classes really quickly since the complexity is low, and it's very straightforward to change the name of an attribute if needed.  This kind of reminds me of the idea of improving readability by breaking up a complicated line of code into multiple lines by defining intermediate variables with descriptive names.

> We definitely appreciate the feedback on the code, though. The `d3` branch is still in a rough alpha stage and there will be a lot of clean up and restructuring in the next few weeks here before we send it to beta, so it might not be worth it to comb through things too carefully quite yet!

If it would be helpful to have an external code reviewer at that point, please do let me know since I'd be happy to help!
