### ISSUE TITLE
Energy Spectrum for Rayleigh Bénard Convection

### ISSUE THREAD

**Issue by chelseajohn** [DedalusProject/dedalus#291]
Hi, I am using Dedalus to solve 2-D Rayleigh Bénard Convection using Dedalus, and I was wondering if there was already some inbuilt function to extract or plot the Kinetic energy spectrum. Any hints are appreciated.

**Comment by kburns** [comment]
Notebook 3 [here](https://kburns.github.io/cism_dedalus_2023/) includes some code for plotting spectra, but since people like to do this in a variety of ways, we generally leave it to the user. Any existing workflow you have for computing spectra from grid data can be used with Dedalus outputs on the grid, too, for periodic problems. Happy to discuss more on the mailing list.
