### ISSUE TITLE
Errors When Building from Source

### ISSUE THREAD

**Issue by yangliu2009** [DedalusProject/dedalus#303]
When building _dedalus_ from source on an Intel CPU, I received the following error 
```
      dedalus/core/transposes.c:2146:3: error: unknown type name ‘MPI_Session’
       2146 |   MPI_Session ob_mpi;
            |   ^~~~~~~
```

[This issue](https://github.com/DedalusProject/dedalus/issues/283) reported the same error message for Apple silicon CPUs. How to fix the issue?

**Comment by yangliu2009** [comment]
The c file "transposes.c" doesn't have 
`#include "mpi4py/mpi4py.h"`
How can transpoes.c find MPI_Session that is defined in mpi4py.h?
`

**Comment by afraser3** [comment]
I believe that the developers ask issues such as this to please be discussed on [the google group](https://groups.google.com/u/1/g/dedalus-users) rather than here. You might try raising this issue there if an initial search reveals this error has not been found before. That said, I wonder if your error is related to [this one](https://groups.google.com/u/1/g/dedalus-users/c/qQZYbcRqbSM), and if the fixes documented there might resolve this issue for you as well.

**Comment by yangliu2009** [comment]
Thanks a lot. The [solution](https://github.com/mpi4py/mpi4py/issues/525) resolved the compile issue, i.e.,

1. Download[ mpi-compat.h](https://github.com/mpi4py/mpi4py/blob/master/demo/wrap-cython/mpi-compat.h) to the mpi4py include directory
2. Add the following code in dedalus/core/transposes.pyx
```
cdef extern from "mpi4py/mpi-compat.h":
    pass
```

**Comment by liamoconnor9** [comment]
Hi @yangliu2009 , could specify where exactly you put the mpi-compat.h file? Thank you
